sudo: required
services:
- docker
script:
- docker build -t ${DOCKER_USER}/logspout ./logspout/
- docker build -t ${DOCKER_USER}/elasticsearch  ./elastic/
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- docker push ${DOCKER_USER}/logspout
- docker push ${DOCKER_USER}/elasticsearch
notifications:
  email: false
