sudo: required
services:
- docker
script:
- wget -O ./logspout/build.sh https://raw.githubusercontent.com/gliderlabs/logspout/master/build.sh
- docker build -t ${DOCKER_USER}/logspout ./logspout/
- docker build -t ${DOCKER_USER}/elasticsearch  ./elastic/
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- docker push ${DOCKER_USER}/logspout
- docker push ${DOCKER_USER}/elasticsearch
notifications:
  email: false
