sudo: required
services:
- docker
script:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- docker build -t ${DOCKER_USER}/elasticsearch  ./elastic/ &&
  docker push ${DOCKER_USER}/elasticsearch
- wget -O ./logspout/build.sh https://raw.githubusercontent.com/gliderlabs/logspout/master/build.sh &&
  chmod +x ./logspout/build.sh &&
  docker build -t ${DOCKER_USER}/logspout ./logspout/ &&
  docker push ${DOCKER_USER}/logspout
notifications:
  email: false
