sudo: required
services:
- docker
script:
- docker build -t vibioh/logspout --rm ./logspout/
- docker build -t vibioh/elasticsearch --rm ./elastic/
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- docker push vibioh/logspout
- docker push vibioh/elasticsearch
notifications:
  email: false
