sudo: required
services:
  - docker
install: make
script:
  - "make"
  - "docker login -e ${DOCKER_EMAIL} -u ${DOCKER_USER} -p ${DOCKER_PASS}"
  - "docker push vibioh/logspout"
notifications:
  email: false
