version: '2'

services:
  elasticsearch:
    image: elasticsearch
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: 'no'

  logstash:
    image: logstash
    hostname: logstash
    environment:
    - TZ=Europe/Paris
    links:
    - elasticsearch:elasticsearch
    command: 'logstash -e "input { gelf { type => docker, port => 12201 } } output { elasticsearch { hosts => elasticsearch } }"'
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: 'no'

  kibana:
    image: kibana
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: kibana.${DOMAIN}'
      traefik.port: '5601'
    links:
    - elasticsearch:elasticsearch
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: 'no'

networks:
  default:
    external:
      name: swarm-net