version: '2'

services:
  tv:
    image: vibioh/http
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: netdata.${DOMAIN}'
      traefik.port: '1080'
    volumes:
    - ${NETDATA_DIR}:/www
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: 'no'
    read_only: true

  netdata:
    image: titpetric/netdata
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: netdata-${NODE}.${DOMAIN}'
      traefik.port: '19999'
    hostname: '${NODE}'
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    cap_add:
    - SYS_PTRACE

networks:
  default:
    external:
      name: traefik
