version: '2'

services:
  elasticsearch:
    image: elasticsearch
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: 'no'

  logstash:
    image: logstash
    command: >
      logstash
      -e 'input {
        udp {
          port => 5000
          codec => json
        }
      }
      output {
        elasticsearch {
          hosts => elasticsearch
        }
      }'
    hostname: logstash
    environment:
    - TZ=Europe/Paris
    - LOGSPOUT=ignore
    links:
    - elasticsearch:elasticsearch
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: 'no'

  kibana:
    image: kibana
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: kibana.${DOMAIN}'
      traefik.port: '5601'
    environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
    - elasticsearch:elasticsearch
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: 'no'

networks:
  default:
    external:
      name: swarm-net