version: '2'

services:
  elasticsearch:
    image: elasticsearch
    labels:
      traefik.enable: 'false'
    volumes:
    - ${ELASTIC_DIR}:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: '-Xms1g -Xmx1g'
    logging:
      driver: json-file
      options:
        max-size: '10m'
    restart: on-failure:5
    cpu_shares: 256
    mem_limit: 1610612736
    security_opt:
    - no-new-privileges

  logstash:
    image: logstash
    command: >
      logstash
      -e 'input {
        udp {
          port => 5000
          codec => json
        }
      }
      output {
        elasticsearch {
          hosts => elasticsearch
        }
      }'
    labels:
      traefik.enable: 'false'
    expose:
    - '5000/udp'
    environment:
      TZ: 'Europe/Paris'
      LOGSPOUT: 'ignore'
    logging:
      driver: json-file
      options:
        max-size: '10m'
    restart: on-failure:5
    cpu_shares: 256
    mem_limit: 536870912
    security_opt:
    - no-new-privileges

  logspout:
    image: vibioh/logspout
    command: 'logstash://logstash:5000'
    labels:
      traefik.enable: 'false'
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    logging:
      driver: json-file
      options:
        max-size: '10m'
    restart: on-failure:5
    cpu_shares: 128
    mem_limit: 33554432
    security_opt:
    - no-new-privileges

  kibana:
    image: kibana
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: kibana.vibioh.fr'
      traefik.frontend.auth.basic: 'vibioh:${KIBANA_PASSWORD}'
      traefik.port: '5601'
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
    logging:
      driver: json-file
      options:
        max-size: '10m'
    restart: on-failure:5
    cpu_shares: 256
    mem_limit: 268435456
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
