version: '2'

services:
  elasticsearch:
    image: vibioh/elasticsearch
    labels:
      traefik.backend.healthcheck.path: '/_cluster/health'
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: elasticsearch.${DOMAIN}'
      traefik.port: '9200'
    volumes:
    - ${ELASTIC_DIR}:/usr/share/elasticsearch/data
    logging:
      driver: json-file
      options:
        max-size: '10m'
    restart: on-failure:5
    cpu_shares: 512
    mem_limit: 1073741824
    security_opt:
    - no-new-privileges

  logstash:
    image: logstash
    command: >
      logstash
      -e 'input {
        udp {
          port => 5000
          codec => json
        }
      }
      output {
        elasticsearch {
          hosts => elasticsearch
        }
      }'
    labels:
      traefik.enable: 'false'
    expose:
    - '5000/udp'
    environment:
    - TZ=Europe/Paris
    - LOGSPOUT=ignore
    links:
    - elasticsearch:elasticsearch
    logging:
      driver: json-file
      options:
        max-size: '10m'
    restart: on-failure:5
    cpu_shares: 256
    mem_limit: 536870912
    security_opt:
    - no-new-privileges

  kibana:
    image: kibana
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: kibana.${DOMAIN}'
      traefik.port: '5601'
    environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    - NODE_OPTIONS=-max-old-space-size=200
    links:
    - elasticsearch:elasticsearch
    logging:
      driver: json-file
      options:
        max-size: '10m'
    restart: on-failure:5
    cpu_shares: 256
    mem_limit: 268435456
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
