version: '2.1'

services:
  logspout:
    image: gliderlabs/logspout
    command: 'syslog+tls://logs${PAPERTRAIL_NUMBER}.papertrailapp.com:${PAPERTRAIL_PORT}'
    labels:
      traefik.enable: 'false'
    environment:
      LOGSPOUT: 'ignore'
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/routes"]
    logging:
      driver: json-file
      options:
        max-size: '10m'
    user: '${CONTAINER_USER}'
    restart: on-failure:5
    cpu_shares: 128
    mem_limit: 33554432
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
