version: '2'

services:
  elasticsearch:
    image: vibioh/elasticsearch
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: elasticsearch.${DOMAIN}'
      traefik.port: '9200'
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: 'no'

  logstash:
    image: logstash
    command: >
      logstash
      -e 'input {
        udp {
          port => 5000
          codec => json
        }
      }
      output {
        elasticsearch {
          hosts => elasticsearch
          protocol => "http"
          user => logstash
          password => P4SSW0RD
        }
      }'
    labels:
      traefik.enable: 'false'
    expose:
    - '5000/udp'
    environment:
    - TZ=Europe/Paris
    - LOGSPOUT=ignore
    links:
    - elasticsearch:elasticsearch
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: 'no'

  kibana:
    image: vibioh/kibana
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: kibana.${DOMAIN}'
      traefik.port: '5601'
    environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    - NODE_OPTIONS=-max-old-space-size=200
    links:
    - elasticsearch:elasticsearch
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: 'no'

networks:
  default:
    external:
      name: swarm-net
