version: '2'

services:
  node:
    image: prom/node-exporter
    labels:
      traefik.enable: 'false'
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 134217728
    security_opt:
    - no-new-privileges

  prometheus:
    image: prom/prometheus
    command: -config.file=/prometheus-data/prometheus.yml
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: prometheus.${DOMAIN}'
      traefik.port: '9090'
    volumes:
    - ${PROMETHEUS_DIR}/prometheus.yml:/prometheus-data/prometheus.yml
    links:
    - node
    logging:
      driver: json-file
      options:
        max-size: '50m' 
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 134217728
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
